dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - tushare
    - seaborn
    - StatModels
    - Keras
    - Gensim
    - missingno
